1 splitting widget and app code
house-of-abbey/GarminHomeAssistantWidget pull request #2
Opened 2024-02-17 18:35 UTC by Someone0nEarth

2024-02-18 12:49 UTC, philipabbey requested changes
Nice. Thank you for doing this and testing. I'll do a round of beta test deployment too shortly.

2024-02-18 12:49 UTC, philipabbey commented on source/HomeAssistantApp.mc
>      function onSettingsChanged() as Void {
Turns out this comment can be removed now. Prompted me to do the same in the application too.

2024-02-18 12:49 UTC, philipabbey commented on export.cmd
> -@echo off
I'm going to suggest we add the equivalent for the widget back in. It makes it really easy to build and then deploy the .IQ file.

Widget version based on https://github.com/house-of-abbey/GarminHomeAssistant/blob/113-splitting-widget-and-app-code/export.cmd#L94 i.e. `--output %SRC%\export\HomeAssistant-widget.iq`.

I can do that if you can't test it.

2024-02-18 13:08 UTC, Someone0nEarth commented on source/HomeAssistantApp.mc
>      function onSettingsChanged() as Void {
Done!

2024-02-18 13:08 UTC, Someone0nEarth commented on export.cmd
> -@echo off
That would be nice. I don`t have a dev environment under a Windows system.

2024-02-18 13:55 UTC, philipabbey commented on export.cmd
> -@echo off
Just testing, then I'll commit the change.

2024-02-18 14:30 UTC, philipabbey commented
@Someone0nEarth Just pushed some trivial changes.
![HomeAssistantWidget_Savings](https://github.com/house-of-abbey/GarminHomeAssistantWidget/assets/24634527/7f40c197-9606-4100-a225-ce9d61fcbe44)
Previously this was at 89%, so 5% improvement which is welcome.

2024-02-18 14:36 UTC, philipabbey commented
@Someone0nEarth I'll await your approval of these changes before merging.

2024-02-18 14:46 UTC, philipabbey approved these changes

2024-02-20 21:00 UTC, philipabbey commented
@Someone0nEarth Are you happy with my few additional changes?

2024-02-21 18:23 UTC, merged

2024-02-21 18:30 UTC, Someone0nEarth commented
> @Someone0nEarth Are you happy with my few additional changes?

Was busy the last days. I changed the app name to "Homeassistant Widget" to be able to differentiate the widget and the app version. But I think without "Widget" is working for me too.

2024-02-21 21:41 UTC, philipabbey commented
> I changed the app name to "Homeassistant Widget" to be able to differentiate the widget and the app version. But I think without "Widget" is working for me too.

Yes, see screenshot above where it was too wide for the watch face.